import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.sql.SQLException;

public class EmprestimoView extends javax.swing.JFrame {
    private DefaultTableModel tableModel;

    public EmprestimoView() {
        tableModel = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "Jogo", "Data Empréstimo", "Data Devolução"}
        ) {
            boolean[] canEdit = new boolean[] {false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        initComponents();
        tabelaEmprestimos.setModel(tableModel);
        carregarJogos();
        atualizarTabela();
    }

    private void carregarJogos() {
        try {
            JogoDAO dao = new JogoDAO();
            List<JogoDTO> jogos = dao.listar();
            jComboBoxJogo.removeAllItems();
            for (JogoDTO jogo : jogos) {
                jComboBoxJogo.addItem(jogo.getIdJogo() + " - " + jogo.getTituloDoJogo() + " (" + jogo.getPlataformaDoJogo() + ")");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar jogos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizarTabela() {
        try {
            EmprestimoDAO dao = new EmprestimoDAO();
            List<EmprestimoDTO> emprestimos = dao.listar();
            tableModel.setRowCount(0);
            JogoDAO jogoDao = new JogoDAO();
            for (EmprestimoDTO emprestimo : emprestimos) {
                JogoDTO jogo = jogoDao.buscarPorId(emprestimo.getIdJogo());
                String tituloJogo = jogo != null ? jogo.getIdJogo() + " - " + jogo.getTituloDoJogo() + " (" + jogo.getPlataformaDoJogo() + ")" : "Jogo Desconhecido";
                tableModel.addRow(new Object[] {
                    emprestimo.getIdEmprestimo(),
                    tituloJogo,
                    emprestimo.getDataEmprestimo(),
                    emprestimo.getDataDevolucao()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar tabela: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGerenciamentoEmprestimo = new javax.swing.JLabel();
        bntVoltar = new javax.swing.JButton();
        lblJogo = new javax.swing.JLabel();
        lblDataEmprestimo = new javax.swing.JLabel();
        txtDataEmprestimo = new javax.swing.JTextField();
        lblDataDevolucao = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JTextField();
        bntRegistarEmprestimo = new javax.swing.JButton();
        bntDevolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();
        jComboBoxJogo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        lblGerenciamentoEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGerenciamentoEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        lblGerenciamentoEmprestimo.setText("Gerenciamento de Emprestimos");

        bntVoltar.setBackground(new java.awt.Color(51, 255, 255));
        bntVoltar.setText("Voltar");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGerenciamentoEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntVoltar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGerenciamentoEmprestimo)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bntVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblJogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJogo.setText("Jogo:");

        lblDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataEmprestimo.setText("Data de Empréstimo (AAAA-MM-DD):");

        txtDataEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEmprestimoActionPerformed(evt);
            }
        });

        lblDataDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataDevolucao.setText("Data de Devolução (AAAA-MM-DD):");

        txtDataDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDevolucaoActionPerformed(evt);
            }
        });

        bntRegistarEmprestimo.setBackground(new java.awt.Color(0, 204, 153));
        bntRegistarEmprestimo.setText("Registrar Emprestimo");
        bntRegistarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistarEmprestimoActionPerformed(evt);
            }
        });

        bntDevolver.setBackground(new java.awt.Color(0, 102, 153));
        bntDevolver.setText("Devolver");
        bntDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDevolverActionPerformed(evt);
            }
        });

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jogo", "Data Empréstimo", "Data Devolução"
            }
        ));
        jScrollPane2.setViewportView(tabelaEmprestimos);

        jComboBoxJogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(bntRegistarEmprestimo)
                        .addGap(72, 72, 72)
                        .addComponent(bntDevolver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataEmprestimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblJogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxJogo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataDevolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJogo)
                    .addComponent(jComboBoxJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataEmprestimo)
                    .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDevolucao)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRegistarEmprestimo)
                    .addComponent(bntDevolver))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntRegistarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistarEmprestimoActionPerformed
        if (jComboBoxJogo.getSelectedIndex() == -1 || txtDataEmprestimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um jogo e informe a data de empréstimo!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dataEmprestimo = txtDataEmprestimo.getText().trim();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(dataEmprestimo);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data de empréstimo inválida! Use AAAA-MM-DD (ex.: 2023-10-15).", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dataDevolucao = txtDataDevolucao.getText().trim();
        if (!dataDevolucao.isEmpty()) {
            try {
                sdf.parse(dataDevolucao);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Data de devolução inválida! Use AAAA-MM-DD (ex.: 2023-10-15).", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        try {
            JogoDAO jogoDao = new JogoDAO();
            List<JogoDTO> jogos = jogoDao.listar();
            int idJogo = -1;
            String jogoSelecionado = jComboBoxJogo.getSelectedItem().toString();
            for (JogoDTO jogo : jogos) {
                String jogoCombo = jogo.getIdJogo() + " - " + jogo.getTituloDoJogo() + " (" + jogo.getPlataformaDoJogo() + ")";
                if (jogoCombo.equals(jogoSelecionado)) {
                    idJogo = jogo.getIdJogo();
                    break;
                }
            }

            if (idJogo == -1) {
                JOptionPane.showMessageDialog(this, "Jogo não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            EmprestimoDTO emprestimo = new EmprestimoDTO();
            emprestimo.setIdJogo(idJogo);
            emprestimo.setDataEmprestimo(dataEmprestimo);
            emprestimo.setDataDevolucao(dataDevolucao.isEmpty() ? null : dataDevolucao);

            EmprestimoDAO dao = new EmprestimoDAO();
            dao.inserir(emprestimo);

            JOptionPane.showMessageDialog(this, "Empréstimo registrado com sucesso!");
            txtDataEmprestimo.setText("");
            txtDataDevolucao.setText("");
            jComboBoxJogo.setSelectedIndex(-1);
            atualizarTabela();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar empréstimo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bntRegistarEmprestimoActionPerformed

    private void bntDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDevolverActionPerformed
        int selectedRow = tabelaEmprestimos.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um empréstimo na tabela!", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    String dataDevolucao = (String) tableModel.getValueAt(selectedRow, 3);
    if (dataDevolucao != null && !dataDevolucao.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Este empréstimo já foi devolvido!", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    tableModel.setValueAt("2023-10-30", selectedRow, 3); // Data fixa para simulação
    JOptionPane.showMessageDialog(this, "Empréstimo devolvido com sucesso!");
    }//GEN-LAST:event_bntDevolverActionPerformed

    private void txtDataEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEmprestimoActionPerformed

    private void txtDataDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDevolucaoActionPerformed

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        JogoCadastroView jogoView = new JogoCadastroView();
    jogoView.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_bntVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDevolver;
    private javax.swing.JButton bntRegistarEmprestimo;
    private javax.swing.JButton bntVoltar;
    private javax.swing.JComboBox<String> jComboBoxJogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataDevolucao;
    private javax.swing.JLabel lblDataEmprestimo;
    private javax.swing.JLabel lblGerenciamentoEmprestimo;
    private javax.swing.JLabel lblJogo;
    private javax.swing.JTable tabelaEmprestimos;
    private javax.swing.JTextField txtDataDevolucao;
    private javax.swing.JTextField txtDataEmprestimo;
    // End of variables declaration//GEN-END:variables
}
